'''Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''


x=1
y=1
z=0

while x<=4000000:
    print(x/2)
    y=x+y
    print(y/2)
    x=x+y

    if x%2==0:
        print('První')
        z=z+x
    
    if y%2==0.0:
        print('Druhá')
        z=z+y
print ('The sum is: '+str(z))
